
import { useState } from 'react';
import { Book, ChevronRight, FileText, Search, CreditCard, Users, Shield, Zap, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface DocItem {
    title: string;
    readTime: string;
    content?: string;
}

interface DocSection {
    category: string;
    icon: any;
    items: DocItem[];
}

const DocumentationPage = () => {
    const navigate = useNavigate();
    const [searchQuery, setSearchQuery] = useState('');
    const [selectedDoc, setSelectedDoc] = useState<DocItem | null>(null);

    const documents: DocSection[] = [
        {
            category: 'Getting Started',
            icon: Zap,
            items: [
                {
                    title: 'Platform Overview',
                    readTime: '3 min read',
                    content: "Welcome to GenMatrix! This platform is designed to help you manage your network and earnings efficiently. Our dashboard provides a comprehensive view of your business performance at a glance."
                },
                {
                    title: 'Setting Up Your Profile',
                    readTime: '5 min read',
                    content: "Your profile is your digital identity on GenMatrix. Ensure your contact information is up to date in the Settings page to receive important notifications and updates."
                },
                {
                    title: 'Understanding Your Dashboard',
                    readTime: '4 min read',
                    content: "The dashboard is your command center. You can track your Personal Volume (PV), Group Volume (GV), recent orders, and network growth in real-time."
                },
            ]
        },
        {
            category: 'Financials & Commissions',
            icon: CreditCard,
            items: [
                {
                    title: 'Compensation Plan Explained',
                    readTime: '10 min read',
                    content: "GenMatrix offers a lucrative compensation plan that rewards both personal sales and team building. Earn commissions through direct referrals, binary team volume, and matching bonuses."
                },
                {
                    title: 'How Withdrawals Work',
                    readTime: '3 min read',
                    content: "Withdraw your earnings securely via our supported payment methods. Navigate to the Wallet page, click 'Withdraw', and follow the prompts. Minimum withdrawal limits may apply."
                },
                {
                    title: 'Understanding PV and GV',
                    readTime: '6 min read',
                    content: "Personal Volume (PV) is generated from your own purchases. Group Volume (GV) is the total volume generated by your entire downline organization. Both are key metrics for rank advancement."
                },
                {
                    title: 'Tax Information',
                    readTime: '4 min read',
                    content: "As an independent distributor, you are responsible for reporting your earnings. You can download your annual earnings report from the financial settings section for tax purposes."
                },
            ]
        },
        {
            category: 'Network Management',
            icon: Users,
            items: [
                {
                    title: 'Building Your Binary Tree',
                    readTime: '8 min read',
                    content: "Success in a binary plan requires balance. Learn how to strategically place new members on your left and right legs to maximize your team commissions."
                },
                {
                    title: 'Enrolling New Members',
                    readTime: '4 min read',
                    content: "Enroll new members easily using your personal referral link or directly through the 'Enroll Member' page in your dashboard."
                },
                {
                    title: 'Placement Strategies',
                    readTime: '7 min read',
                    content: "Effective placement is crucial. Consider placing strong leaders in key positions to drive growth in both legs of your organization."
                },
            ]
        },
        {
            category: 'Security & Compliance',
            icon: Shield,
            items: [
                {
                    title: 'KYC Verification Process',
                    readTime: '3 min read',
                    content: "To ensure platform security and regulatory compliance, all members must complete KYC (Know Your Customer) verification. Upload a valid government ID to verify your account."
                },
                {
                    title: 'Account Security Best Practices',
                    readTime: '5 min read',
                    content: "Protect your account by using a strong password and enabling Two-Factor Authentication (2FA) in your security settings. Never share your login credentials."
                },
                {
                    title: 'Compliance Guidelines',
                    readTime: '6 min read',
                    content: "Adhere to our compliance guidelines when promoting GenMatrix. Avoid making income claims that are not substantiated by typical results."
                },
            ]
        }
    ];

    const filteredDocs = documents.map(section => ({
        ...section,
        items: section.items.filter(item =>
            item.title.toLowerCase().includes(searchQuery.toLowerCase())
        )
    })).filter(section => section.items.length > 0);

    if (selectedDoc) {
        return (
            <div className="max-w-4xl mx-auto space-y-6 animate-fade-in-up">
                <button
                    onClick={() => setSelectedDoc(null)}
                    className="flex items-center gap-2 text-gray-500 hover:text-teal-600 transition-colors font-medium text-sm group"
                >
                    <div className="bg-white dark:bg-[#1a1b23] p-1.5 rounded-lg border border-gray-200 dark:border-white/10 group-hover:border-teal-500/50 shadow-sm">
                        <ArrowLeft size={16} />
                    </div>
                    Back to Documentation
                </button>

                <div className="bg-white dark:bg-[#1a1b23] rounded-2xl border border-gray-200 dark:border-white/5 p-8 md:p-12 shadow-sm">
                    <div className="flex items-center gap-3 mb-6">
                        <div className="bg-teal-50 dark:bg-teal-500/10 p-2 rounded-lg">
                            <FileText size={24} className="text-teal-600 dark:text-teal-400" />
                        </div>
                        <div className="text-sm font-semibold text-teal-600 dark:text-teal-400 uppercase tracking-widest">
                            Guide
                        </div>
                    </div>

                    <h1 className="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-4 leading-tight">
                        {selectedDoc.title}
                    </h1>

                    <div className="flex items-center gap-4 text-sm text-gray-500 dark:text-gray-400 mb-8 pb-8 border-b border-gray-100 dark:border-white/5">
                        <span className="flex items-center gap-1.5">
                            <Book size={14} />
                            {selectedDoc.readTime}
                        </span>
                        <span>•</span>
                        <span>Last updated: just now</span>
                    </div>

                    <div className="prose dark:prose-invert max-w-none text-gray-600 dark:text-gray-300 leading-relaxed">
                        <p className="text-lg">
                            {selectedDoc.content || "Content coming soon..."}
                        </p>
                        <p>
                            Detailed documentation content would go here. This includes step-by-step instructions, screenshots, and further explanations tailored to the specific topic.
                        </p>
                        <p>
                            For more Assistance, please contact our support team.
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <button
                onClick={() => navigate('/dashboard/help')}
                className="flex items-center gap-2 text-gray-500 hover:text-teal-600 transition-colors font-medium text-sm group"
            >
                <div className="bg-white dark:bg-[#1a1b23] p-1.5 rounded-lg border border-gray-200 dark:border-white/10 group-hover:border-teal-500/50 shadow-sm">
                    <ArrowLeft size={16} />
                </div>
                Back to Help Center
            </button>

            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Documentation</h1>
                    <p className="text-gray-500 dark:text-gray-400 mt-1">
                        Detailed guides and resources to help you master the platform.
                    </p>
                </div>

                <div className="relative w-full md:w-64">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={18} />
                    <input
                        type="text"
                        placeholder="Search guides..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full pl-10 pr-4 py-2 bg-white dark:bg-[#1a1b23] border border-gray-200 dark:border-white/10 rounded-xl focus:outline-none focus:ring-2 focus:ring-teal-500 text-sm text-gray-900 dark:text-white"
                    />
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {filteredDocs.map((section) => (
                    <div key={section.category} className="bg-white dark:bg-[#1a1b23] rounded-2xl border border-gray-200 dark:border-white/5 overflow-hidden">
                        <div className="p-6 border-b border-gray-200 dark:border-white/5 bg-gray-50/50 dark:bg-white/[0.02]">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-lg bg-teal-50 dark:bg-teal-500/10 flex items-center justify-center text-teal-600 dark:text-teal-400">
                                    <section.icon size={20} />
                                </div>
                                <h2 className="text-lg font-bold text-gray-900 dark:text-white">
                                    {section.category}
                                </h2>
                            </div>
                        </div>

                        <div className="divide-y divide-gray-100 dark:divide-white/5">
                            {section.items.map((item, index) => (
                                <button
                                    key={index}
                                    onClick={() => setSelectedDoc(item)}
                                    className="w-full flex items-center justify-between p-4 hover:bg-gray-50 dark:hover:bg-white/[0.02] transition-colors group text-left"
                                >
                                    <div className="flex items-center gap-3">
                                        <FileText size={16} className="text-gray-400 group-hover:text-teal-500 transition-colors" />
                                        <span className="text-sm font-medium text-gray-700 dark:text-gray-200 group-hover:text-teal-600 dark:group-hover:text-teal-400 transition-colors">
                                            {item.title}
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-3">
                                        <span className="text-xs text-gray-400 font-medium">
                                            {item.readTime}
                                        </span>
                                        <ChevronRight size={14} className="text-gray-300 group-hover:text-teal-500 transition-colors" />
                                    </div>
                                </button>
                            ))}
                        </div>
                    </div>
                ))}
            </div>

            {filteredDocs.length === 0 && (
                <div className="text-center py-12">
                    <Book className="w-12 h-12 text-gray-300 mx-auto mb-4" />
                    <h3 className="text-lg font-medium text-gray-900 dark:text-white">No results found</h3>
                    <p className="text-gray-500 dark:text-gray-400 mt-1">
                        Try searching for something else or browse our categories.
                    </p>
                </div>
            )}
        </div>
    );
};

export default DocumentationPage;
